controller/securenaming.go, controller/securenaming_test.go
=> add license headers

cert_manager/BUILD, cert_manager/generate_cert.go, cmd/generate_cert/BUILD, cmd/generate_cert/main.go
=> Add cert generation lib and tool.

controller/securenaming.go, controller/securenaming_test.go, controller/storage.go
* Wrap extra long lines
* Add/Fix comments for public methods and structs
* Always check the error returned by a method
* Use narrow interfaces
This closes #19 and is a precommit for #22 .
=> Fix linter violation in controller, including

.travis.yml, bin/bazel_to_go.py, bin/linters.sh
=> Enable GoMetaLinter in Travis

certmanager/BUILD, certmanager/ca.go, controller/BUILD, controller/secret.go, controller/secret_test.go
This is the first commit towards #3 .
=> Add SecretController that watches service accounts to create key & cert

certmanager/BUILD, certmanager/generate_cert.go, certmanager/generate_cert_test.go, cmd/generate_cert/main.go, controller/BUILD
=> Add unit test for generate_cert.go

.travis.yml, bin/headers.sh
=> Add a script to detect whether go files contain copyright headers

controller/securenaming_test.go
=> Fix flakey tests in securenaming

certmanager/ca.go, certmanager/generate_cert.go, certmanager/generate_cert_test.go, cmd/generate_cert/main.go
=> Make key size configurable

controller/secret.go, controller/secret_test.go
=> Better handling existing secret

Jenkinsfile
=> Add Jenkinsfile to push docker image after a commit is submitted

controller/BUILD, controller/secret.go, controller/secret_test.go
This enables us to only list and watch relevent secrets, instead of all
secrets
=> Set the secret type to isito.io/key-and-cert

controller/secret.go, controller/secret_test.go
=> Auto refreshing secrets before the contained cert expires

WORKSPACE
=> Fix go build

Jenkinsfile, WORKSPACE, bin/toolbox/presubmit/BUILD, bin/toolbox/presubmit/package_coverage_check.py, codecov.requirement
https://github.com/istio/istio-testing/issues/135
Add a step to check if the code coverage meets requirement in every specific package.
=> Add package code coverage check

WORKSPACE, bin/toolbox/presubmit/BUILD, bin/toolbox/presubmit/package_coverage_check.py
https://github.com/istio/toolbox/issues/2
=> Merge toolbox to test-infra

certmanager/ca.go, certmanager/ca_test.go, cmd/istio_ca/main.go
=> Make the issue org of self-signed cert configurable

.gitignore, Jenkinsfile
=> Update auth for qualification to follow same pattern as mixer and manager

bin/get_workspace_status, cmd/istio_ca/BUILD, cmd/istio_ca/main.go, cmd/istio_ca/version/BUILD, cmd/istio_ca/version/version.go, cmd/istio_ca/version/version_test.go, tools/bazel.rc
=> Add version command

README.md
Mostly about wrapping up long lines
=> Re-format README.md

Jenkinsfile, WORKSPACE, bin/e2e.sh, integration/BUILD, integration/main.go
* Add bin/e2e.sh that is called by Jenkins to build and push up a
container image
* Add integration/ executable which deployes Istio CA into testing
cluster and check `istio.default` secret is created
More tests will be added in following PRs
This PR is part of #115
=> Set up integration test framework

controller/secret.go, controller/secret_test.go, integration/BUILD, integration/main.go
=> Integration tests: test secret type and secret data content

Jenkinsfile, bin/check_build_files.sh, bin/install-prereqs.sh, node_agent/BUILD, node_agent/na/BUILD, pkg/pki/BUILD, utils/BUILD
And fix issues with existing BUILD files
=> Add a script to check BUILD files are properly configured

certmanager/ca.go, certmanager/generate_cert.go, certmanager/generate_cert_test.go, pkg/pki/crypto.go, pkg/pki/crypto_test.go
This avoids us to explicitly pass key algorithm as a parameter
=> Parse private key based on PEM block type

Jenkinsfile, bin/e2e.sh, bin/push-docker.sh, prow/auth-postsubmit.sh, prow/auth-presubmit.sh
- Simplify Jenkins workflows.
- Fix docker push
- Add integration tests as part of postsubmit
=> Enable Postsubmit on Prow

README.md
* Remove build status icon since we no longer uses Jenkins
* Add Go Report Card
=> Update icons in README

.gitignore
=> Git ignore generated protobuf files

cmd/istio_ca/main.go
=> Remove unnecessary check for certChain parameter since it can be empty

node_agent/na/nodeagent.go
=> Add more log to node agent

cmd/istio_ca/main.go, node_agent/main.go, node_agent/na/BUILD, node_agent/na/nodeagent.go, pkg/pki/crypto.go
Tests with some necessary refactoring will be added in the next PR.
```release-note
NONE
```
=> Add retries for node agent cert requests. Add grace period to the cert renew interval.

cmd/node_agent/BUILD, cmd/node_agent/main.go, cmd/node_agent/na/nafactory.go, cmd/node_agent/na/nodeagent.go, cmd/node_agent/na/onprem.go
Use Cobra to parse CLI.
This fixes issue #226.
```release-note
Use cobra to parse CLI
```
=> Use cobra to parse CLI

cmd/node_agent/main.go, cmd/node_agent/na/nodeagent.go, cmd/node_agent/na/onprem.go
=> Setup proper path for node_agent

pkg/server/grpc/server.go
=> Add comments about the order of authenticators

integration/main.go
```
NONE
```
This fixes #115 
/assign @wattli 
/assign @myidpt
=> Test that a deleted secret is re-created by Istio CA

bin/push-debian.sh, bin/release.sh
```
Build and push Debian package as part of the release
```
=> Build and push Debian package as part of the release

bin/push-debian.sh, prow/auth-postsubmit.sh, prow/auth-presubmit.sh, tools/deb/BUILD
Update script to use the right tag when creating the debian package.
```release-note
none
```
=> Upload Debian for pre and post submit

tools/deb/istio-auth-node-agent.service
```release-note
Fix startup for the debian files for standalone node agent.
```
=> Fix the systemd manifest to use the correct binary name

cmd/istio_ca/BUILD, cmd/istio_ca/main.go, pkg/pki/ca/BUILD, pkg/pki/ca/ca.go, pkg/pki/ca/ca_test.go
… write it to secret for persistency
```release-note
NONE
```
=> Store self-signed key/cert in secret so next time CA does not regenerate

bin/linters.sh, integration/BUILD, integration/main.go
=> Fix integration test failure due to RBAC enablement

Makefile, bin/linters.sh, bin/setup.sh, prow/auth-presubmit.sh
=> Add Makefile and use fixed linter

bin/linters.sh, integration/BUILD, integration/main.go
Automatic merge from submit-queue
Fix integration test failure due to RBAC enablement
```release-note
none
```
```release-note
```
=> Fix integration test failure due to RBAC enablement (#296)

WORKSPACE, cmd/node_agent/na/BUILD, cmd/node_agent/na/aws.go, cmd/node_agent/na/aws_test.go, cmd/node_agent/na/gcp_test.go
=> add signature verification and unit tests for AWS plugin
