certmanager/ca.go
certmanager/generate_cert.go
certmanager/generate_cert_test.go
cmd/generate_cert/main.go

IMO this makes the API more consistent and avoid most translates between time string and time.Time object.

Use time.Time instead of string for notBefore/notAfter in CertOptions

---

certmanager/generate_cert.go
cmd/generate_cert/main.go

This allows us to generate root/intermediate CA certicates.
Fix #46

Make host optional

---

certmanager/ca.go
certmanager/ca_test.go
certmanager/generate_cert.go
certmanager/generate_cert_test.go
certmanager/util.go
certmanager/util_test.go

This method will be used by the secret controller to re-parse
certificate saved into a secret to examine certificate expiration time.

Expose ParsePemEncodedCertificate in certmanager

---

controller/secret.go
controller/secret_test.go

Later we will also have handlers for secrets, so renaming these methods
to avoid confusion.

Rename event handling methods for service accounts

---

WORKSPACE
cmd/istio_ca/BUILD
cmd/istio_ca/main.go
docker/BUILD

This allows us to later register subcommand such as `istio-ca version`
as requested in #111

Use cobra for command line processing

---

bin/e2e.sh
integration/main.go

glog prepends "ERROR: logging before flag.Parse:" to each log message
if `flag.Parse()`. However we can't simply call `flag.Parse()` since
CLI options are handled by cobra.
This PR manually forces `flag.Parsed()` to return true to avoid those
annoying messages.
Logic is borrowed from
https://github.com/istio/mixer/blob/master/cmd/server/cmd/root.go#L44

Stop glog from emitting false negative errors

---

integration/main.go

Because it makes little sense to expose such a method in the
integration package.

Make `AddFlags` private

---

certmanager/ca.go
certmanager/ca_test.go
certmanager/generate_cert.go
certmanager/generate_cert_test.go
controller/secret.go
pkg/pki/crypto.go
pkg/pki/crypto_test.go

This allows caller to deal with errors directly and makes testing
easier.

Return error instead of logging it

---

certmanager/generate_cert_test.go

This makes it possible to later move this function into for example
`pkg/pki` and share it between unit test and integration test.

Make `verifyCert` return error, instead of calling `t.Error()`

---

cmd/generate_cert/BUILD
cmd/generate_cert/main.go
cmd/generate_csr/BUILD
cmd/generate_csr/main.go
cmd/istio_ca/BUILD
cmd/istio_ca/main.go
codecov.requirement
controller/BUILD
controller/secret.go
controller/secret_test.go
node_agent/na/BUILD
node_agent/na/nodeagent.go
pkg/credential/BUILD
pkg/credential/token.go
pkg/pki/ca/BUILD
pkg/pki/ca/ca.go
pkg/pki/ca/ca_test.go
pkg/pki/ca/generate_cert.go
pkg/pki/ca/generate_cert_test.go

Specifically, CA related methods are moved into /pkg/pki/ca; GCP token
fetcher is moved into /pkg/credential/

Refactor: move /certmanager into /pkg

---

WORKSPACE

This is not used and is the source of the annoying warning about switch
from `new_go_repository` to `go_repository`.

Remove unnecessary rules in WORKSPACE

---

node_agent/na/nodeagent.go
proto/ca_service.proto

Changes include:
* Rename `CertificateSigningRequest` to just `Request`
(`CertificateSigningRequest` has a specific meaning within PKI and we
shouldn't redefine it)
* Correspondingly, `CertificateSigningResponse` is renamed to `Response`
* Change `csr` to `csr_pem` to signify the encoding requirement on the
bytes

Update proto definition

---

.github/PULL_REQUEST_TEMPLATE.md
OWNERS

Add required files for Mungegithub.
OWNERS file defines who can approve prs in this repo and who are recommended reviewer.
PR template helps people add release-note when creating prs. Simply add release-note or "NONE" between ```, then mungegithub will add proper release-note label. More details at https://github.com/istio/istio/pull/525
More details about [Mungegithub](https://github.com/istio/test-infra/tree/master/mungegithub/deployment)
[Related pr](https://github.com/istio/mixer/pull/1024)

Add OWNERS and pr template for mungegithub

---

cmd/istio_ca/main.go
pkg/pki/ca/ca.go
pkg/pki/ca/ca_test.go
pkg/pki/ca/controller/secret_test.go
pkg/server/grpc/BUILD
pkg/server/grpc/server.go
pkg/server/grpc/server_test.go

```
GRPC service is now served over TLS
```

Run GRPC server over TLS

---

pkg/pki/BUILD
pkg/pki/ca/ca_test.go
pkg/pki/ca/generate_cert.go
pkg/pki/san.go
pkg/pki/san_test.go

This will be used by the grpc server for client certificate based
authN/authZ.
Also grouping all SAN-related operations into package `pkg/pki/san.go`
```
NONE
```

Add a method to extract identities from SAN extension

---

cmd/istio_ca/main.go

/assign @wattli
/cc @rshriram
```
The default self-signed CA root cert TTL is extended to be 1 year
```

Extend default CA root cert TTL to 1 year

---

cmd/istio_ca/BUILD
cmd/istio_ca/main.go
cmd/node_agent/BUILD
cmd/node_agent/main.go
integration/BUILD
integration/main.go
pkg/cmd/BUILD
pkg/cmd/flag.go

This should fix the "logging before flag.Parse" error as below
```
ERROR: logging before flag.Parse: I0823 15:56:28.415665   14113 main.go:154] Use self-signed certificate as the CA certificate
ERROR: logging before flag.Parse: I0823 15:56:28.792499   14113 main.go:137] Istio CA has started
ERROR: logging before flag.Parse: I0823 15:56:28.792522   14113 server.go:107] Starting GRPC server on port 3443
ERROR: logging before flag.Parse: I0823 15:56:28.837063   14113 secret.go:189] Istio secret for service account "default" in namespace "grpc-testing" has been created
```
/assign @myidpt 
/assign @wattli 
```release-note
```

Set flag.Parsed() to be true and carry over glog flags

---

integration/main.go
pkg/pki/ca/ca.go
pkg/pki/ca/ca_test.go
pkg/pki/ca/controller/secret.go
pkg/pki/ca/controller/secret_test.go
pkg/pki/ca/generate_cert.go
pkg/server/grpc/server_test.go

Currently the CA exposes two methods:
* `Sign(csrPEM []string)` which is used by the GRPC server
* `Generate(name, namespace []string)` which is used for generating
cert based on K8S service account.
However these two methods are very similar, and this PR removes the
second method completely. After this PR, the K8S secret controller
constructs a CSR locally and uses the `Sign` method to get a
certificate.
```
NONE
```

Unifying CA signing interface

---

bin/linters.sh

Fixed the following linter warning:
```
WARNING: staticcheck, gosimple and unused are all set, using megacheck instead
```
```NONE
```

Use megacheck instead of running staticcheck, gosimple and unsued

---

pkg/pki/ca/generate_cert_test.go

The flakyness was due to we set the NotBefore field to current time.
However when verifying the cert, the NotBefore field is required to be
strictly earlier than the time at which verification happens. Thus
test fails occasionally if there isn't sufficient time elapsed between
cert issuance and cert verification.
Fixes #253
```NONE
```
/assign @wattli

Fix test flakyness in generate_cert_test.go

---

WORKSPACE
cmd/istio_ca/BUILD
cmd/istio_ca/main.go
cmd/istio_ca/markdown.go

```
Add `markdown` subcommand to auto generate documentation for istio_ca 
```
/assign @wattli 
/assign @myidpt

Add markdown subcommand to generate documentation for istio_ca

---

BUILD.ubuntu
WORKSPACE
cmd/node_agent/main.go
cmd/node_agent/na/BUILD
cmd/node_agent/na/aws.go
cmd/node_agent/na/nafactory.go
docker/BUILD
pkg/credential/BUILD
pkg/credential/token.go
tools/deb/BUILD

First step in supporting AWS. To make it truly work we'll need some refactoring in the codebase. For example, `na.createRequest()` needs to be pluggable to correctly populate `NodeAgentCredentials` field in request message.
```release-note
none
```

Add preliminary AWS support for node agent

---

tools/deb/BUILD
tools/deb/istio-auth-node-agent.service

Cherry pick of #270 
Fix auth node agent start error issue (wrong file name)
Fixes `_` /`-` typo in binary name
also without putting generic named binaries in user’s /usr/local/bin
Actual fix for #268 
```release-note
Standalone node agent path fix (debian)
```
(cherry picked from commit f6efb0ab402ae55b7ba5b7b249e3df312422258d)

Fix auth node agent start error issue (in release-0.2 branch)

---

cmd/node_agent/na/BUILD
cmd/node_agent/na/aws.go
cmd/node_agent/na/gcp.go
cmd/node_agent/na/nafactory.go
cmd/node_agent/na/nodeagent.go
cmd/node_agent/na/nodeagent_test.go
cmd/node_agent/na/onprem.go
pkg/credential/BUILD
pkg/credential/token.go
proto/ca_service.proto

```release-note
NONE
```
Haven't found a good way to test `aws.go` yet...

Add credential_type field in Request proto definition
